### ISSUE TITLE
Path for properties is hard-coded

### ISSUE THREAD

**Issue by wwadge** [n0mer/gradle-git-properties#1]
https://github.com/n0mer/gradle-git-properties/blob/master/src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy#L31

The plugin writes directly to build folder. Under IDE, the build folder is not monitored for resources during debugging (it looks at src/main/resources instead).

Can you make the destination configurable (in my case I'd set it to src so that during compilation it will then be copied over to build)

**Comment by n0mer** [comment]
@wwadge please try `1.4.6` version of plugin - it is already available from gradle plugin repository.

You can set custom directory location like this:

```groovy
gitProperties {
    gitPropertiesDir = new File("${project.rootDir}/your/custom/dir")
}
```

Please share whether this works for you or not.

**Comment by wwadge** [comment]
Works fine. Thanks a lot!


gitProperties {
    gitPropertiesDir = new File("${project.sourceSets.main.resources.srcDirs[0]}")
}

**Comment by n0mer** [comment]
:+1:
