### ISSUE TITLE
Add support for Heroku builds/deploys

### ISSUE THREAD

**Issue by balteo** [n0mer/gradle-git-properties#10]
Hi,
It seems the gradle git plugin does not work with Heroku (the gradle buildpack). The plugin works a charm locally but when I deploy my app on Heroku through github I get this:

```
Execution failed for task ':bignibou-server:generateGitProperties'.
       > org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /tmp/build_4554f9f0f404781365e453846c38e499/silteo-bignibou-site-ad93e406ac8e613a615778d617498dd057043ace
```

**Comment by n0mer** [comment]
@balteo , can you please elaborate on why do you think  that there is a bug in plugin and the issue is not heroku-specific?

looks like some repository is not found

**Comment by balteo** [comment]
Hello Nikolay,
Indeed. I checked with them and the repository is not present. Hence the
issue. Can you close the issue please?
Regards,
Julien.

2016-03-14 3:33 GMT+01:00 Nikolay Gorylenko <notifications@github.com>:

**Comment by n0mer** [comment]
@balteo sure - good luck with your project :)

**Comment by atodd-noms** [comment]
Some explanation of how you solved this would be helpful. I have the same problem. How did you get this working on Heroku?

**Comment by kurtseebauer** [comment]
`generateGitProperties {
    onlyIf {
        !source.isEmpty() 
    }
}`
does the "trick" of not generating the git.properties file, but it seems there is no easy way to get git information in heroku builds. I asked the heroku guys and here is the response:

> I'm afraid there's not an easy workaround I can think of - Heroku deploys remove the .git folder early on in the build process which makes it difficult to use git based tools. One alternative would be to extract the git properties on your local machine as part of your deploy process and add them to the repo at that point.
> 
> Another (more complicated) option would be to clone the repository to the dyno in a separate folder as part of the build process. You might be able to use https://github.com/weibeld/heroku-buildpack-run for this.
> 
> Let me know if you have any further questions.
