### ISSUE TITLE
Support multiple line commit messages

### ISSUE THREAD

**Issue by pedro-carneiro** [n0mer/gradle-git-properties#106]
I'm not entirely sure if this is an issue for this plugin or not, but full commit messages that span multiple lines are not set correctly in the `git.properties` file. Example:
```
git.commit.message.full=The title
The message first line
The message second line
```

The message should be set like:
```
git.commit.message.full=The title\
The message first line\
The message second line
```

**Comment by tha2015** [comment]
Yes, it is an known bug in v1.4.21 (see https://github.com/n0mer/gradle-git-properties/issues/28).
The fix for the issue will be in the next release (v1.5.0).

**Comment by pedro-carneiro** [comment]
Alright, thank you!
