### ISSUE TITLE
Error using version 1.5.0 | Execution failed for task ':generateGitProperties'.

### ISSUE THREAD

**Issue by varunmehta** [n0mer/gradle-git-properties#107]
spring-boot-version: 1.5.13

plugin version: 
``` id "com.gorylenko.gradle-git-properties" version "1.5.0"```

```* What went wrong:
...
11:57:03.314 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve org.eclipse.jgit.ui.jar (org.eclipse.jgit:org.eclipse.jgit.ui:5.0.0.201805301535-rc2)' completed
... 
11:57:03.323 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve org.eclipse.jgit.jar (org.eclipse.jgit:org.eclipse.jgit:5.0.0.201805301535-rc2)' completed
...
Execution failed for task ':generateGitProperties'.
> No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (java.lang.String) values: [HEAD]
  Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()```

**Comment by cdmbr** [comment]
Temporary kludge to avoid this error:

```
classpath ("gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:+") {
    exclude group: "org.eclipse.jgit", module: "org.eclipse.jgit"
}
classpath "org.eclipse.jgit:org.eclipse.jgit:4.11.+"
```

**Comment by tha2015** [comment]
If possible, can you provide a minimal build.gradle to reproduce the issue? Thanks.

**Comment by tha2015** [comment]
Never mind, I can reproduce the issue now. Will provide a fix soon. Thanks for reporting.

**Comment by tha2015** [comment]
This issue comes from grgit 2.1.1 which being used by this plugin (see https://github.com/ajoberstar/grgit/issues/229 ). Specifically, grgit 2.1.1 using jgit with dynamic version range, so jgit 4.x is upgraded automatically to jgit 5.x when 5.x available recently (which is not backward compatible to 4.x).

Solution: We will need to upgrade the plugin dependency from grgit 2.1.1 to grgit 2.2.1 (using static version of jgit)

**Comment by tha2015** [comment]
I have delivered the fix for this issue. 

@n0mer Can you help to publish a new version to fix this critical issue soon? Thanks.

**Comment by tha2015** [comment]
@varunmehta  @cdmbr  New version v1.5.1 is just published thanks to @n0mer

**Comment by varunmehta** [comment]
Tested and works! Thanks a lot guys.
