### ISSUE TITLE
Upgrade gradle-git dependency version (currently 1.4.2) to avoid annoying jgit message (Cannot run program "bash")

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#11]
Whenever running the build with this plugin, I see below message (from jgit 3.x ) although everything works well

> java.io.IOException: Cannot run program "bash" (in directory "..."): CreateProcess error=2, The system cannot find the file specified

If gradle-git version can be updated to a newer version  (1.4.x), it will use new jgit 4.x and this message will not be displayed anymore. (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463349)

Thanks.

**Comment by n0mer** [comment]
@tha2015 i published `1.4.12` - please confirm that this solves your problem

**Comment by tha2015** [comment]
I tested with 1.4.12 and it fixed my issue. Thank you for the great work.
