### ISSUE TITLE
Improve doc for manifest example

### ISSUE THREAD

**Issue by sdavids** [n0mer/gradle-git-properties#110]
Please add the following snippet to your _generated properties_ section:

```
bootJar {
  manifest {
    attributes(
        'Build-Revision': "${-> project.ext.gitProps['git.commit.id.abbrev']}"
    )
  }
}
```

Non-Gradle/Groovy experts might wonder why ` 'Build-Revision': project.ext.gitProps['git.commit.id.abbrev']` does not work.

**Comment by tha2015** [comment]
Please verify the changes at https://github.com/n0mer/gradle-git-properties . Thanks.
