### ISSUE TITLE
Detect git branch name for multibranch pipeline Jenkins projects and detect branch names on other build servers (Bamboo, Gitlab, Teamcity etc )

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#115]
For multibranch pipeline Jenkins projects: See https://jenkins.io/doc/book/pipeline/multibranch/
For other build servers: See https://github.com/ktoso/maven-git-commit-id-plugin/tree/master/src/main/java/pl/project13/maven/git/build

**Comment by bamapookie** [comment]
I have this problem with Jenkins as well.  when building from a multibranch pipeline, the branch is reported as "HEAD".

**Comment by tha2015** [comment]
Code was delivered to master branch. Should be included in next release (v1.5.3?)
