### ISSUE TITLE
generateGitProperties shows UP-TO-DATE after executing clean task

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#12]
If generateGitProperties task generated git.properties and then the file is deleted (manually or by gradle clean), executing generateGitProperties task again will NOT re-generate the git.properties (because gradle thinks the output is UP-TO-DATE)
This is something related to gradle cache folder (.gradle/)  of project folder so step 1 below is important to reproduce the issue

[rep1.zip](https://github.com/n0mer/gradle-git-properties/files/172447/rep1.zip)

Steps to reproduce:  (sample project is attached)

1. Delete build/ and .gradle/ from the project folder (if any). This step is important.
  ```
  c:\rep1> rmdir /s /q .gradle
  c:\rep1> rmdir /s /q build
  ```

2. Run gradle jar to generate git.properties
  ```
  c:\rep1> gradle jar
  :compileJava
  :generateGitProperties
  :processResources UP-TO-DATE
  :classes
  :jar

  BUILD SUCCESSFUL
  ```
3. Run gradle clean to delete build/ folder
  ```
  c:\rep1> gradle clean
  :clean

  BUILD SUCCESSFUL
  ```
4. Run gradle jar again and verify that the git.properties is not re-generated
  ```
  c:\rep1> gradle jar
  :compileJava
  :generateGitProperties UP-TO-DATE
  :processResources UP-TO-DATE
  :classes
  :jar

  BUILD SUCCESSFUL
  ```
  The git.properties is not generated because (:generateGitProperties UP-TO-DATE)
5. System information:
  ```
  C:\rep1>gradle -v

  ------------------------------------------------------------
  Gradle 2.12
  ------------------------------------------------------------

  Build time:   2016-03-14 08:32:03 UTC
  Build number: none
  Revision:     b29fbb64ad6b068cb3f05f7e40dc670472129bc0

  Groovy:       2.4.4
  Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
  JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
  OS:           Windows 7 6.1 amd64
  ```

**Comment by n0mer** [comment]
@tha2015 

maybe this is caused by code from PR #4

```groovy
task.inputs.dir(new File(project.gitProperties.gitRepositoryRoot ?: project.rootProject.file('.'),".git"))
```

**Comment by n0mer** [comment]
@tha2015 while fixing #9 i ended up with file re-creation every time plugin is executed.

Can you please try recent 1.4.14 version?

**Comment by tha2015** [comment]
I verified with the new version and it fixed the issue. Thanks.

**Comment by tha2015** [comment]
Sorry. I closed the issue by mistake. It still happens on v 1.4.14

**Comment by tha2015** [comment]
I made some changes to the plugin and it worked correctly. The modified file is attached 
[GitPropertiesPlugin.groovy.zip](https://github.com/n0mer/gradle-git-properties/files/175409/GitPropertiesPlugin.groovy.zip)

Basically I removed the logic from GitPropertiesPlugin class
```
        task.inputs.dir(new File(project.gitProperties.gitRepositoryRoot ?: project.rootProject.file('.'),".git"))

        def dir = project.gitProperties.gitPropertiesDir ?: new File(project.buildDir, "resources/main")
        task.outputs.file(new File(dir, "git.properties"))
```
and added logic to GenerateGitPropertiesTask class
```
        @InputFiles
        public FileTree getSource() {
            return project.files(new File(project.gitProperties.gitRepositoryRoot ?: project.rootProject.file('.'),".git")).getAsFileTree()
        }

        @OutputFile
        public File getOutput() {
           def dir = project.gitProperties.gitPropertiesDir ?: new File(project.buildDir, "resources/main")
           return new File(dir, "git.properties")
        }
```

**Comment by n0mer** [comment]
@tha2015 please try v1.4.15

**Comment by tha2015** [comment]
Just tried v 1.4.15 and it fixed my issue. Thanks.

**Comment by ghilainm** [comment]
For me this issue still occurs all the time. The up-to-date check is never true. I am using version 2.2.0.

Here is how I apply the plugin

```groovy
project.plugins.apply(GitPropertiesPlugin)
        project.gitProperties {
            keys = [
                    'git.branch',
                    //Those properties are disabled to benefit from build cache (https://github.com/n0mer/gradle-git-properties/issues/116)
                    //'git.build.host',
                    //'git.build.time',
                    //'git.build.user.email',
                    //'git.build.user.name',
                    'git.build.version',
                    'git.closest.tag.commit.count',
                    'git.closest.tag.name',
                    'git.commit.id',
                    'git.commit.id.abbrev',
                    'git.commit.id.describe',
                    'git.commit.message.full',
                    'git.commit.message.short',
                    'git.commit.time',
                    'git.commit.user.email',
                    'git.commit.user.name',
                    'git.dirty',
                    'git.remote.origin.url',
                    'git.tags',
                    'git.total.commit.count'
            ]
        }
        //Expose GIT properties in git extension automatically
        project.extensions.gitProperties.extProperty = "git"
```

**Comment by tha2015** [comment]
When you configure extProperty, you want the git properties map (extProperty) to used by other task(s).  The mentioned logic (upToDateWhen) is to make sure that gradle-git-properties will always execute to populate the git properties map (so it can be used by other tasks).

Does it impact to your build somehow? Any suggestion to fix it?

**Comment by ghilainm** [comment]
It does not really impact my build but I was frustrated to not have up to date status!

Isn't there any call back in Gradle which could be executed to perform this after the up-to-date check of the task?  So that it is always executed even if the main task is not?

**Comment by tha2015** [comment]
I worry that filling the map object extProperty without executing the task would make the plugin hard to understand (and potentially causing new issues).

Do you need extProperty for other tasks to use? Maybe you should remove extProperty and have the UP-TO-DATE status again? ^^
