### ISSUE TITLE
Support for Gradle 5.X

### ISSUE THREAD

**Issue by ghilainm** [n0mer/gradle-git-properties#123]
It seems there is an issue with the library you use and Gradle 5.X.

See here for more details: https://github.com/ajoberstar/gradle-git/issues/276

**Comment by tha2015** [comment]
Thanks for the report. I will update the dependency as soon as grgit 3.0 is released.

To clarify: we are using grgit 2.2.1, not gradle-git which is not supported anymore

**Comment by tha2015** [comment]
I found only 3.0.0-beta.1 at https://github.com/ajoberstar/grgit

**Comment by tha2015** [comment]
I have updated the plugin dependency to use grgit-core 3.0.0-beta.2 in commit d6e6282
This is a major change, so the plugin version is updated to 2.0.0-beta1

**Comment by tha2015** [comment]
Gradle 5.x is supported in new plugin release (v2.0.0-beta1)

**Comment by mrcasablr** [comment]
grgit 3.0 was released Nov 14, 2018. - https://github.com/ajoberstar/grgit/releases

Any plans to do a GA release of 2.0?

**Comment by tha2015** [comment]
Commit ID 1d3a0abdba69d308338e27e0998478746e1f7eb3

**Comment by tha2015** [comment]
Fixed in v2.0.0
