### ISSUE TITLE
Remove "git.build.time" property because it is not so useful and causing issues (file will always be re-generated)

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#129]
Remove "git.build.time" property because it is not so useful and causing issues (file will always be re-generated). The users who need a build stamp or something similar can always add it via customProperty config

**Comment by tha2015** [comment]
Fixed. Will be in next release v2.1.0.

**Comment by poznachowski** [comment]
Any plans for 2.1.0 release?

**Comment by tha2015** [comment]
Sorry, not at the moment. There are two issues which I would like to resolve before we have next release.

**Comment by tha2015** [comment]
v2.1.0 is now published.
