### ISSUE TITLE
Enhancement request: could you provide configuration key to format the date in git.commit.time

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#13]
It would be great if we can configure a date format like "yyyy-MM-dd'T'HH:mm'Z'" to format the git.commit.time value.
Thanks.

**Comment by tha2015** [comment]
It would be easier to read a formatted date comparing to a timestamp

**Comment by n0mer** [comment]
AFAIK, maven `git-properties` plugin does not support this.

Personally i'm using this via spring-boot-admin, and i would direct this `timestamp formatting` question there.

**Comment by tha2015** [comment]
I don't know about git-properties maven plugin and I don't know how sprint-boot-admin works so I have no comment about that. But for maven-git-commit-id-plugin (which is mentioned in Spring Boot documentation), I see date format options like `dateFormat` and `dateFormatTimeZone ` (see 
https://github.com/ktoso/maven-git-commit-id-plugin) and I believe that that plugin generates formatted dates (not Spring Boot does it).

**Comment by n0mer** [comment]
@tha2015 you are right - other plugins are just displayed whatever is present in .properties file under specific key.

personally i like the idea of human-readable build dates; will have time to implement this in approximately 1 month, not right now. meanwhile can only review PR, if there is any.

**Comment by tha2015** [comment]
Created pull request https://github.com/n0mer/gradle-git-properties/pull/15

**Comment by n0mer** [comment]
merged #15  and published new version `1.4.16`

thank you @tha2015
