### ISSUE TITLE
Customize generate file-name

### ISSUE THREAD

**Issue by predhme** [n0mer/gradle-git-properties#130]
It appears as though one can override the location of the generated file. However, it doesn't appear that the filename itself can be overridden:

https://github.com/n0mer/gradle-git-properties/blob/974716a25729d581a060add6f3de841fb070339e/src/main/groovy/com/gorylenko/GenerateGitPropertiesTask.groovy#L127

**Comment by tha2015** [comment]
Yes, it should be configurable. 
BTW, just for my curiosity, do you know any case which needs to use a different file name?

**Comment by predhme** [comment]
We are not using Spring Boot (at least not yet), but we have a use case to generate a file with information from Git, as well as other data. For instance, we are taking version information from Gradle and appending it to the file. We wanted to rename the file to "version.properties" so that the name of the file is more reflective of what it represents to our application.
