### ISSUE TITLE
Add the `gitProperties` to the build.gradle.kts

### ISSUE THREAD

**Issue by jbohnvn** [n0mer/gradle-git-properties#136]
I have a springboot project using Kotlin and gradle.

I want to change the folder and file name of git.properties.
I added below piece of code to `build.gradle.kts` file, but I'm getting the following error `Unresolved reference: gitPropertiesDir` in intellij

`gitProperties {
    gitPropertiesDir = "${project.rootDir}/your/custom/dir"
}`

Could somebody help me to resolve it?

**Comment by tha2015** [comment]
Try to Refresh several times from Gradle view. 

I'm attaching a sample project which worked for me. Try to import to your IntelliJ to see if it works for you.
[testapp.zip](https://github.com/n0mer/gradle-git-properties/files/3622979/testapp.zip)

**Comment by jbohnvn** [comment]
Thanks a lot @tha2015 
I tried to rebuild project in intelliJ then the issue has been resolved
