### ISSUE TITLE
gradle :generateGitProperties success but not file was generated

### ISSUE THREAD

**Issue by Jeansen** [n0mer/gradle-git-properties#137]
I've got a Kotlin project, added the plugin and - just for a test - and ran: `gradle generateGitProperties

Her's what happened:

```
BUILD SUCCESSFUL in 680ms
1 actionable task: 1 executed
```

But no file was produced. What am I missing?

------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          13 (Oracle Corporation 13+33)
OS:           Linux 5.2.0-3-amd64 amd64

**Comment by tha2015** [comment]
Can you try with -debug option to see what happened?

**Comment by Jeansen** [comment]
Oh, forget that I mentioned anything. As always, the idiot (me) sits in front of the screen ;-(
I simply forgot to apply the plugin after adding it to the plugins section. Well, I am still new to gradle (lame excuse).
