### ISSUE TITLE
Wrong git.closest.tag.name value

### ISSUE THREAD

**Issue by alesbukovsky** [n0mer/gradle-git-properties#138]
The `git.closest.tag.name` is not correct. Here is the head part my current branch commit history:
```
6bdb.. (HEAD -> develop, tag: v1.6.0, origin/master, origin/develop, master) chore(release): 1.6.0
a00d.. feat: add social interactions to reporting
a036.. feat: add viewed recipes and restaurant guides to reporting
f0e0.. feat: add reporting for read articles
57c1.. chore: upgrade to Spring Boot 2.1.9
d2d9.. chore: minor GitLab pipeline streamlining
688d.. chore: split aptible setup pipeline out by environment
3e33.. (tag: v1.5.0) chore(release): 1.5.0
af49.. chore: hook semantic release handling to GitLab pipeline
d0e.. fix: failed docker image build in gitlab pipeline
cc8c.. fix: invalid cookie expires header
8cb.. feat: external program enrollment verification
8ec0.. chore: upgrade to Spring Boot 2.1.8 and Gradle 5.6.2
3bbf.. docs: clean up and update README documentation
caeb.. (tag: v1.4.0) fix: adjusted kick-off for non-physical activity
2494.. fix: database connection failure to verify hostname
...
```
My expectation is that the closest tag should be `v1.6.0` and the value of `git.closest.tag.commit.count` should be 0. 

Instead the closest tag is recorded as `v1.4.0` with the commit count of 14. So the tag is wrong although its distance from HEAD is calculated correctly.  

Interestingly enough, the value of `git.tags` lists only `v1.6.0`, which appears correct assuming these are the tags that are on the same commit hash as the current HEAD. 

When the HEAD was on the tag `v1.5.0` few weeks ago, the generated properties were correct. Back then, as well as today, the plugin version used was **2.1.0**. Even after upgrading to **2.2.0** it is still picking up the wrong tag.

**Comment by tha2015** [comment]
I suspect that your tag is not annotated tag so it is not displayed by 'git describe' command. The reason for this is to be consistent with maven git plugin.
A workaround is to use custom property (see Readme doc).

**Comment by alesbukovsky** [comment]
That's probably the case:
```
git show-ref -d --tags
5acd63885ba9f3d1ef8f49051683604c216801a3 refs/tags/v1.0.0
35f921812be615fc7d5b5fda92d3cd138c9366e9 refs/tags/v1.0.0^{}
1bab7659f03667c40a8456bc2a6c5acac6414156 refs/tags/v1.1.0
c3f92a0b84f8a86275188d0cdba1e14dc847e8f9 refs/tags/v1.1.0^{}
ad00a20587c912a7136c24bf404cf4f6f2cd7755 refs/tags/v1.2.0
3881ed4d80b3487637837fc25f66fe369ce47787 refs/tags/v1.2.0^{}
b3e7663d16285cd433a93b11888d7f3eee41034b refs/tags/v1.3.0
ee31b69c7b977cb80440023db7c33ce55c7208a3 refs/tags/v1.3.0^{}
5577b2b9f8a86b38c867adbc16add0d03c50a87c refs/tags/v1.4.0
caeb35eee0b0e849ccb5053529ad8c2e05161e36 refs/tags/v1.4.0^{}
3e3349516c3b3f4d3211ad5489f5695bd961542e refs/tags/v1.5.0
6bdb082cbd807e08180458959b6d0c3119ea6577 refs/tags/v1.6.0
```

Although I am still puzzled why 1.5.0 worked for me.

**Comment by alesbukovsky** [comment]
Thanks for a quick response. I will look at the custom property override, or parse the {git.tags}}.
