### ISSUE TITLE
don't fail build during task run when no .git directory is available

### ISSUE THREAD

**Issue by aaditya-taparia** [n0mer/gradle-git-properties#145]
Currently, if there is no .git directory available it seems like `generateGitProperties` fails

**Comment by tha2015** [comment]
Can you try this config? It should do the job.

```
gitProperties {
    failOnNoGitDirectory = false
}
```

**Comment by tha2015** [comment]
FYI, I've updated the README at https://github.com/n0mer/gradle-git-properties

**Comment by aaditya-taparia** [comment]
Thanks!
