### ISSUE TITLE
[Question] Issue with GString lazy evaluation when using Kotlin DSL

### ISSUE THREAD

**Issue by x80486** [n0mer/gradle-git-properties#147]
I'm using Gradle `6.2.2` with your plugin: `com.gorylenko.gradle-git-properties` (version `2.2.2`). I'm trying to "translate" the following (working all fine) snippet into Kotlin DSL:

```groovy
gitProperties {
  extProperty = "gitProps" // git properties will be put in a map at project.ext.gitProps
}

shadowJar {
  manifest {
    attributes(
      "Build-Revision": "${ -> project.ext.gitProps["git.commit.id"]}"  // Uses GString lazy evaluation to delay until git properties are populated
    )
  }
}
```

...but this what I've come up with so far:

```kotlin
gitProperties {
  extProperty = "gitProps"
  keys = listOf("git.branch", "git.build.host", "git.build.version", "git.commit.id", "git.commit.id.abbrev",
      "git.commit.time", "git.remote.origin.url", "git.tags", "git.total.commit.count")
}

tasks {
  withType<ShadowJar> {
    manifest.attributes.apply {
      put("Build-Revision", "${project.ext.properties["git.commit.id"]}")
    }
  }
}
```

I can't figure out to make the "GString lazy evaluation" part working in Kotlin DSL, nor how the `gitProps` map fits on here; eventually that approach (which I know it's partially wrong) is returning `null`.

> StackOverflow question: https://stackoverflow.com/questions/60743468/gstring-lazy-evaluation-in-kotlin-dsl-using-gradle-git-properties-plugin

Is there anything we need to do in order for this plugin to work with Kotlin DSL, specifically what I'm trying to achieve? If not, would you think it's possible to update the documentation to reflect that?

**Comment by ttha1** [comment]
The logic` "Build-Revision": "${ -> project.ext.gitProps["git.commit.id"]}"` is to delay evaluating the value when `shadowJar` is configured (the value is not available in configuration phase). 

I assume that a Groovy closure will also work (haven't tried it yet), you don't have to look for something like GString in Kotlin. 

So I believe that in Kotlin, it could be replaced by a Kotlin closure (note: I don't know Kotlin, this is just my assumption)

```
    manifest {
      attributes(mapOf(
        "Build-Revision" to closureOf<String> { ... }
      ))
    }
```

Let me know how it works in Kotlin and I can update the README

**Comment by x80486** [comment]
That didn't work for me:

```shell
* What went wrong:
Cannot get non-null extra property 'gitProps' as it does not exist
```

I also tried in this way...but same error message:

```kotlin
  withType<ShadowJar> {
    val lazyValue: String? by lazy {
      val gitProps: Map<String, String> by project.ext
      gitProps["git.commit.id"]
    }

    manifest.attributes.apply {
      put("Implementation-Version", lazyValue)
  }
```

Somehow, the Gradle version never evaluates that expression until it's executed.

**Comment by tha2015** [comment]
You can run with -debug flag to see if the git properties plugin was executed before the error. A log file or example project would really helpful.

**Comment by x80486** [comment]
All right! If you clone [this repo](https://github.com/x80486/kotlin-dsl-git-props/), you will have what I'm trying to do.

**Comment by tha2015** [comment]
@x80486 My theory is not correct, sorry about that. Jar plugin will not execute closures to get manifest attribute values. It will call `toString() `method. So we need some object with a toString() method which will return the value we want. I tried the below logic and it worked for me (it is not good because I have zero knowledge about Kotlin)
```Kotlin
put("Implementation-Version", object {
  override fun toString():String = (project.extra["gitProps"] as Map<String, String>)["git.commit.id"]!!
})

```

**Comment by x80486** [comment]
I think you nailed it. It works for me...thanks a lot! :innocent:

**Comment by tha2015** [comment]
Added to README.md
https://github.com/n0mer/gradle-git-properties/blob/master/README.md
Thanks.
