### ISSUE TITLE
Add Kotlin DSL examples to README.md

### ISSUE THREAD

**Issue by demtnt** [n0mer/gradle-git-properties#148]
I would be very useful to add Kotlin DSL example to README.md. Because I've spent 2-3 hours to find out how to replace Grovy:
`gitProperties {
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "PST"
}`
to Kotlin DSL
`configure<com.gorylenko.GitPropertiesPluginExtension> {
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
}`

**Comment by tha2015** [comment]
Thanks, will do.

**Comment by tha2015** [comment]
Done.
https://github.com/n0mer/gradle-git-properties/blob/master/README.md
