### ISSUE TITLE
Getting the git.branch name as "HEAD" when gradle build is executed on Gitlab CI

### ISSUE THREAD

**Issue by rohitkashyapvatta** [n0mer/gradle-git-properties#150]
I am getting git.branch name as "HEAD" when the gradle build is executed on Gitlab CI and looked at the latest code where you have mentioned it is going to read the GIT LOCAL BRANCH but in my case it is still showing HEAD.

if I use the following:
gitProperties {
    branch = System.getenv('GIT_BRANCH')
}

then it says : "No such property: branch for class: com.gorylenko.GitPropertiesPluginExtension_Decorated.

Steps I followed:
1. Created a property file using this.
gitProperties {
    gitPropertiesDir = "${project.rootDir}/your/custom/dir"
}
2. Add the above gitProperties again

and when triggered the gradle build got the above error message.

**Comment by tha2015** [comment]
I assume that you are using latest version of the plugin?

**Comment by rohitkashyapvatta** [comment]
Yes I am using v2.2.2

**Comment by tha2015** [comment]
Thanks Rohit. I haven't had time to try it yet. At the same time, if you
can upload a simple example for the issue, it would be great.

**Comment by tha2015** [comment]
@rohitkashyapvatta 

I tested with a gradle project and it worked for me. Also tried with latest gradle version and it worked correctly. 

So please check:

1. System.getenv('GIT_BRANCH')  does return some value. Note that if GIT_BRANCH system environment doesn't exist, plugin will use repo branch (HEAD) as fallback value

2. The error "No such property: branch" seems to come from an old version somewhere (maybe you have multiple versions used in different subprojects and you forgot to upgrade one of them)

**Comment by tha2015** [comment]
I assumed that you have resolved the issue, so closing the ticket. Please feel free to reopen if you still have the issue.

**Comment by spyro2000** [comment]
I have the same problem with 2.2.4 (also GitLab):

![image](https://user-images.githubusercontent.com/8479925/122183647-bb1dcb00-ce8b-11eb-86a5-7c43f557967d.png)
