### ISSUE TITLE
No git.properties file generated with Gradle 4.10.3

### ISSUE THREAD

**Issue by antbewes** [n0mer/gradle-git-properties#157]
The following is not generating the git.properties file: 

`>gradlew clean build`

Called explicitly however it is working:

`>gradlew  generateGitProperties`

Here's part of my build.gradle file, and I'm using Java 8
```
buildscript {
   ...
       dependencies {
        classpath "gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.2.4"
    }
}
apply plugin: "com.gorylenko.gradle-git-properties"

```

**Comment by tha2015** [comment]
This task depends on "classes" task if project is a Java project (i.e. using Java plugin).
Can you try "./gradlew classes -debug" to see why the plugin was not executed?

**Comment by antbewes** [comment]
It's working as expected now. I suspect I was building via IntelliJ which was using the /out/ dir instead which is known not to work. Thank-you
