### ISSUE TITLE
Support config-cache

### ISSUE THREAD

**Issue by wyhasany** [n0mer/gradle-git-properties#160]
When I run my application with `config-cache`. I receive warns that `gradle-git-properties` doesn't support it. 
![image](https://user-images.githubusercontent.com/317662/109393321-4006c800-7921-11eb-86fd-8c4aa0529f89.png)
It seems like [Undeclared reading of environment properties](https://docs.gradle.org/6.8.3/userguide/configuration_cache.html#config_cache:requirements:undeclared_env_var_read).

Do you think you can resolve it to support configuration cache?

Status of community plugins:
https://github.com/gradle/gradle/issues/13490

**Comment by ttha1** [comment]
Thanks for reporting the issue. I will have a look into it soon.

**Comment by tha2015** [comment]
Thanks for reporting the issue. I will have a look into it soon.
