### ISSUE TITLE
jcenter shutdown is planned

### ISSUE THREAD

**Issue by cjr333** [n0mer/gradle-git-properties#166]
I heard of jcenter shutdown and found that gradle-git-properties use jcenter as repositories.
(https://blog.gradle.org/jcenter-shutdown)

Do you have a plan to change gradle repositories?

**Comment by joschi** [comment]
@cjr333 From [JCenter shutdown impact on Gradle builds](https://blog.gradle.org/jcenter-shutdown):

> Publishing new plugins
> 
> If you are publishing your plugin with the `com.gradle.publish-plugin`, you are not affected. Just double check that your build does not use JCenter directly.

And from that blog post:

> We will automatically migrate all plugins published to Bintray on March 31, 2021. After that date, we will no longer synchronize plugins published to Bintray. This migration should be transparent to users resolving dependencies.

So I think we're safe. 😉 
https://github.com/n0mer/gradle-git-properties/blob/643136727ca66c43a3726f8ac1dd9d7d074e029c/build.gradle#L4

**Comment by tha2015** [comment]
Actually we have jcenter repo in build.grade at https://github.com/n0mer/gradle-git-properties/blob/643136727ca66c43a3726f8ac1dd9d7d074e029c/build.gradle#L16
