### ISSUE TITLE
Support Gradle 7

### ISSUE THREAD

**Issue by swanandvk** [n0mer/gradle-git-properties#173]
Plugin doesn't work with gradle 7

**Comment by joschi** [comment]
@swanandvk Could you please elaborate on your issue?

- What exactly doesn't work?
- What's the exact error message?
- Could you provide a minimal example demonstrating your issues?

**Comment by swanandvk** [comment]
@joschi sure 

* What went wrong:
After upgrading to gradle version 7 , the build is failing with the error message
```

Some problems were found with the configuration of task ':application:generateGitProperties' (type 'GenerateGitPropertiesTask').
  - Type 'GenerateGitPropertiesTask' property 'gitProperties' is missing an input or output annotation.
    Reason: A property without annotation isn't considered during up-to-date checking.
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
```

**Comment by joschi** [comment]
@swanandvk Which version of this plugin are you using?

**Comment by markusheiden** [comment]
Using adoptopenjdk 16, sourceCompatibility = JavaVersion.VERSION_16

2.2.4 produces 
Task :generateGitProperties FAILED
Caught exception during close(): groovy.lang.MissingPropertyException: No such property: out for class: com.gorylenko.writer.NormalizeEOLOutputStream

2.3.0 produces 
Could not determine the dependencies of task ':bootJar'.
Could not create task ':classes'.
 Gradle#projectsEvaluated(Closure) on build 'xxx' cannot be executed in the current context.

2.3.1-rc produces
An exception occurred applying plugin request [id: 'org.gradle.java']
Failed to apply plugin class 'org.gradle.api.plugins.JavaBasePlugin'.
Task with name 'classes' not found in root project 'xxx'.

When removing the plugin the build (gradlew clean assemble) succeeds.

**Comment by markusheiden** [comment]
The issue with 2.2.4 seems to be jdk 16 related. When using jdk 15 it works.

**Comment by joschi** [comment]
There are a lot of things mixed up here. 😓

> 2.2.4 produces

See https://github.com/n0mer/gradle-git-properties/issues/171#issuecomment-817569604

> 2.3.0 produces

This is (unfortunately) a known broken release as stated in the README.
https://github.com/n0mer/gradle-git-properties/issues/169

> 2.3.1-rc produces

https://github.com/n0mer/gradle-git-properties/issues/169
https://github.com/n0mer/gradle-git-properties/pull/174

**Comment by usr42** [comment]
Version `2.2.4` and `2.3.1-rc` are working for me. (Kotlin project with JDK11)

**Comment by swanandvk** [comment]
> @swanandvk Which version of this plugin are you using?

@joschi 2.2.0

**Comment by joschi** [comment]
> @joschi 2.2.0

Try version `2.3.1-rc`.

**Comment by swanandvk** [comment]
@joschi  2.2.4 worked ✅

**Comment by librucha** [comment]
Version 2.3.x on gradle 7.0 and OpenJDK 14,16 fires error:
```
Could not determine the dependencies of task ':jar'.
> Could not create task ':classes'.
   > Gradle#projectsEvaluated(Closure) on build 'superman-cave' cannot be executed in the current context.
```

**Comment by joschi** [comment]
@librucha Try version 2.3.1-rc.

**Comment by librucha** [comment]
@joschi If you ment version "2.3.1-rc1" this is the same problem. 
```
An exception occurred applying plugin request [id: 'org.gradle.java']
> Failed to apply plugin class 'org.gradle.api.plugins.JavaBasePlugin'.
   > Task with name 'classes' not found in root project 'superman-cave'.
```
It was the reason why i used "version 2.3.x" in previous post. ;)

**Comment by shalugin** [comment]
@swanandvk please try version 2.3.1-rc3

**Comment by DuncanCasteleyn** [comment]
Tried running on Java 16 and Gradle 7.0 with 2.3.1-rc3 and this works fine for me.

**Comment by librucha** [comment]
> @swanandvk please try version 2.3.1-rc3

For me is working. thanks.

**Comment by joschi** [comment]
@tha2015 Since the latest changes all seem to be working, should we close this PR and release gradle-git-properties 2.3.1?

**Comment by tha2015** [comment]
@joschi Sure, v2.3.1 has been published.

**Comment by joschi** [comment]
@swanandvk Should we close this issue since the latest release is working with Gradle 7?
