### ISSUE TITLE
Bintray is shutting down

### ISSUE THREAD

**Issue by remy-tiitre** [n0mer/gradle-git-properties#180]
Have you taken the necessary steps to prepare for bintray shutdown? https://plugins.gradle.org/docs/bintray

I can't use 2.3.1 version, will get an error:
```
> Could not find gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.3.1.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/gradle/plugin/com/gorylenko/gradle-git-properties/gradle-git-properties/2.3.1/gradle-git-properties-2.3.1.pom
  If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
  Required by:
      unspecified:unspecified:unspecified
```

When I open this url it will redirect me to https://jcenter.bintray.com/gradle/plugin/com/gorylenko/gradle-git-properties/gradle-git-properties/2.3.1/gradle-git-properties-2.3.1.pom which made me think that you haven't done this migration that Gradle Plugin portal is guiding to do.

**Comment by joschi** [comment]
The plugin is being published with the Gradle Plugin Publish plugin as recommended by https://plugins.gradle.org/docs/bintray and with gradle-git-properties 2.3.1 having been published on 29 April 2021 (i. e. after the 1 April 2021 deadline mentioned in the article) it should be alright.

https://github.com/n0mer/gradle-git-properties/blob/d5e95f0b3f36409bcfd7c8b44fd48f1ee2fa3764/build.gradle#L5

FWIW, I couldn't reproduce your issue with a new Gradle project with the following `build.gradle` file:
```gradle
plugins {
  id "com.gorylenko.gradle-git-properties" version "2.3.1"
}
```

Which version of Gradle are you using?
How are you referring to the plugin in your build files?

**Comment by remy-tiitre** [comment]
What happens, when you open this url in your browser: https://plugins.gradle.org/m2/gradle/plugin/com/gorylenko/gradle-git-properties/gradle-git-properties/2.3.1/gradle-git-properties-2.3.1.pom, for me it redirects to jcenter.bintray.com for some reason.

I apply it in init script but it should not matter. I commented out this in my init script:
```
settingsEvaluated { settings ->
    settings.pluginManagement {
        repositories {
            gradlePluginPortal()
        }
    }
}
```
And thats how I apply it in my init script:
```
initscript {
    repositories {
        gradlePluginPortal()
    }

    dependencies {
        classpath 'gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.3.1'
    }
}

allprojects {
    plugins.withId('org.springframework.boot') {
        pluginManager.apply(com.gorylenko.GitPropertiesPlugin)
    }

    plugins.withId('com.gorylenko.gradle-git-properties') {
        gitProperties {
            if (System.getenv('CI')) {
                branch = System.getenv('CI_COMMIT_REF_NAME')
            }
            keys = ['git.branch', 'git.commit.id', 'git.commit.time', 'git.dirty']
        }
    }
}
```

**Comment by joschi** [comment]
> ```groovy
>     dependencies {
>         classpath 'gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.3.1'
>     }
> ```

The referenced artifact coordinates are incorrect.

Please use the coordinates documented at https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties/2.3.1.

**Comment by remy-tiitre** [comment]
Yeah, I missed that it had changed. Its working now.
