### ISSUE TITLE
How to use this with GitLab (branch name always 'HEAD')?

### ISSUE THREAD

**Issue by spyro2000** [n0mer/gradle-git-properties#182]
Hi there,

really loving this plugin but as GitLab always checks out all branches in detached state, the branch name will always have the value 'HEAD'.

I tried to resolve this by providing a fallback as an environment variable:

(gitlab-ci.yml):

![image](https://user-images.githubusercontent.com/8479925/122267969-cac50000-cedb-11eb-8009-2f202c3a6c7a.png)

(build.gradle.kts)

![image](https://user-images.githubusercontent.com/8479925/122268027-ddd7d000-cedb-11eb-8c06-1235e847ef2d.png)

But the result is still the same:

![image](https://user-images.githubusercontent.com/8479925/122267873-af59f500-cedb-11eb-9285-fd04400d850e.png)

What am I doing wrong here? Is there any other workaround?

Thank you!

**Comment by tha2015** [comment]
Normally, the plugin will try to use the system environment variable `CI_COMMIT_REF_NAME` when running with GitLab
Ref: 
https://github.com/n0mer/gradle-git-properties/blob/d5e95f0b3f36409bcfd7c8b44fd48f1ee2fa3764/src/main/groovy/com/gorylenko/properties/BranchProperty.groovy#L17

But I'm seeing you are providing a banch name which comes from comes from `GIT_BRANCH` system env var

`branch = System.getenv('GIT_BRANCH')`

Can you try to use `CI_COMMIT_REF_NAME` system env var instead?

`branch = System.getenv('CI_COMMIT_REF_NAME')`

I wonder why it didn't work for you, from GitLab document, the branch name should be available under `CI_COMMIT_REF_NAME` system env var
Ref:  https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables

**Comment by spyro2000** [comment]
Hello tha2015 and many thanks for your quick response,

I'll guess, it might be a problem that it is a docker-based build. So maybe the ENV var doesn't make it into this environment and is than set to a blank.

I tried to pass this variable to the script, but it seems not to work:

> $ export GIT_BRANCH = "$CI_COMMIT_REF_NAME" /bin/sh: export: line 129: : bad variable name

So maybe it's not a fault of your plugin but from our docker configuration.

**Comment by spyro2000** [comment]
UPDATE: It works! :)
I just need to pass the variable down to the docker file! :)

### Step 1: .git.lab-ci.yml

```
# in "variables" top level element
variables:
   GIT_BRANCH: $CI_COMMIT_REF_NAME`
````
...

```
# on job level (calls docker.sh shell script)
  variables:
    GIT_BRANCH: $CI_COMMIT_REF_NAME
````

### Step 2: docker.sh (which calls the actual docker build)
```
docker build (...) build-arg GIT_BRANCH="${GIT_BRANCH}"
````

### Step 3: docker.build.Dockerfile
```
FROM ...
ARG GIT_BRANCH="detached"
ENV GIT_BRANCH=${GIT_BRANCH}
RUN gradle clean build ...
````

### Step 4: build.gradle.kts / build.gradle
```
gitProperties {
    keys = listOf("git.branch", "git.commit.id", "git.commit.time", "git.closest.tag.name")
    failOnNoGitDirectory = false
    branch = System.getenv("GIT_BRANCH") // fallback for gitlab / docker build
}
````

Now it works :)

![image](https://user-images.githubusercontent.com/8479925/122389045-cd256980-cf70-11eb-83b4-0a18fa3a91de.png)

**Comment by tha2015** [comment]
Glad that it works for you now! Thanks for the update.
