### ISSUE TITLE
missing some field of info endpoint 

### ISSUE THREAD

**Issue by foxundermoon** [n0mer/gradle-git-properties#19]
this is my /info endpoint response

``` json
{"git":{"branch":"master","commit":{"id":"0349e1a","time":"1467786845"}}}
```

**Comment by n0mer** [comment]
what is missing @foxundermoon  ?

**Comment by Endron** [comment]
Even more important: Can you post the content of the generated git.properties file?
The endpoint itself is part of Spring Boot Actuator while this plugin only creates the properties file used by the endpoint. So if the properties are correct it is a problem on the Spring side of things.

**Comment by foxundermoon** [comment]
@Endron  @n0mer   
the git.properties is rich.
just  spring boot's show less.
I create custom Endponit to show all the git.properties.
 at the begining i think the  /info Endponit is the plugin generate.

**Comment by mjustin** [comment]
@foxundermoon — Spring Boot will only show some of the information in this file.  You can have it show more information by setting the "management.info.git.mode" property to "full" per [the Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-git), e.g. in application.properties:

`management.info.git.mode=full`

**Comment by searhiy** [comment]
Hi! Can you update usage section in README.md about "full" mode? 

Thank you!

**Comment by n0mer** [comment]
@searhiy README.md updated as per commit 2eb005001035c2e585f7289ab44f99ccde906bce , thanks for pointing out. Closing this issue
