### ISSUE TITLE
Version `2.3.1` stopped working with Java 8

### ISSUE THREAD

**Issue by gotson** [n0mer/gradle-git-properties#195]
Suddenly my project throws this exception when running with Java 8. It works fine with Java 11.

```
FAILURE: Build failed with an exception.

* Where:
Build file 'build.gradle.kts' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.gorylenko.gradle-git-properties', version: '2.3.1']
> Failed to apply plugin 'com.gorylenko.gradle-git-properties'.
   > Could not create an instance of type com.gorylenko.GitPropertiesPluginExtension.
      > org/eclipse/jgit/api/errors/JGitInternalException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Version `2.3.1` has not been updated recently, so i'm not sure what's going on.

**Comment by KENNYSOFT** [comment]
ajoberstar/grgit#339

**Comment by gotson** [comment]
Here is a workaround to force the transitive version of JGit used by the plugin:

```kts
buildscript {
  dependencies {
    "classpath"("org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r") {
      isForce = true
    }
  }
}
```

**Comment by huangjunbiao** [comment]
I have the same problem.I found a new version:2.4.0-rc1 in https://plugins.gradle.org/.It seems to be working but i am not sure the 2.4.0-rc1 Version is available.

**Comment by croqueGrec09** [comment]
I have the same with version 2.2.4 and workaround does not work

**Comment by douph1** [comment]
with old gradle 6.8.3 replace 
`isForce = true`
with
`force = true`
for the workaround from @gotson
Thanks you @gotson

**Comment by gotson** [comment]
> with old gradle 6.8.3 replace `isForce = true` with `force = true` for the workaround from @gotson Thanks you @gotson

`isForce` is for Kotlin Script, `force` is for Groovy. See https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#forced_dependencies_vs_strict_dependencies for more details

**Comment by gotson** [comment]
I have updated my snippet above to provide both Kotlin Script and Groovy.

**Comment by kazukikawaguchi1108** [comment]
it also works like this
※with gradle 6.7.1

```
configurations.all {
    resolutionStrategy.force "org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r"
}
dependencies {
    classpath "gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.2.4"
}
```
thanks you @gotson

**Comment by croqueGrec09** [comment]
The workaround works locally; howewer, when deploying with Jenkins on server, I get following error message:

`
Could not resolve all dependencies for configuration ':classpath'.
Could not resolve org.eclipse.jgit:org.eclipse.jgit:latest.release.
Required by:
 project : > gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.2.4 > org.ajoberstar.grgit:grgit-core:4.1.0
Could not resolve org.eclipse.jgit:org.eclipse.jgit:latest.release.
Failed to list versions for org.eclipse.jgit:org.eclipse.jgit.
Unable to load Maven meta-data from https://repo.grails.org/core/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml.
Could not GET 'https://repo.grails.org/core/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml'.
Received fatal alert: handshake_failure
`

**Comment by dcebotarenco** [comment]
with Gradle 5

configurations.all {
    resolutionStrategy.force "org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r"
}
dependencies {
        classpath 'com.gorylenko.gradle-git-properties:gradle-git-properties:2.3.1'
 }

**Comment by paulosousadias** [comment]
with Gradle 7.3

buildscript {
    dependencies {
        classpath ('org.eclipse.jgit:org.eclipse.jgit:') {
            version {
                strictly '5.13.0.202109080827-r'
            }
        }
    }
}

**Comment by tha2015** [comment]
Version 2.3.2 (based on 2.3.1 tag) has been published with the fix from @KENNYSOFT 
https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties/2.3.2

**Comment by tha2015** [comment]
Version 2.4.0-rc2 (based on master) has been published with the fix from @KENNYSOFT 
https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties

**Comment by tha2015** [comment]
Hi @KENNYSOFT ,
Version 2.4.0 has been released with this fix. Thanks a lot!
-Thai
