### ISSUE TITLE
JGit cannot find org.slf4j.impl.StaticLoggerBinder due to relocation

### ISSUE THREAD

**Issue by lynxplay** [n0mer/gradle-git-properties#203]
The gradle git properties plugin [relocates](https://github.com/n0mer/gradle-git-properties/blob/master/build.gradle#L54) the entire grgit library to a prefixed `gradlegitproperties` package.

Due to the nature of the shadow plugin, the `slf4j-api` included by `jgit` also has its import for `org.slf4j.impl.StaticLoggerBinder` relocated to `gradlegitproperties.org.slf4j.impl.StaticLoggerBinder`. As a result of this, the plugin does not find the gradle logging implementation when running, causing the rather unfortunate error message:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by remal** [comment]
@n0mer could you please exclude slf4j from the relocation process to make the plugin use Gradle's logging infrastructure?

**Comment by n0mer** [comment]
@remal Semyon can you submit PR for this feature request , with test cases

**Comment by lynxplay** [comment]
Is there anything that I can do to speed up resolving this issue ? I understand if the PR I proposed (especially regarding the integration testing) is not ready for a merge as is, I'd be happy to work with the maintainers here to get this or a similar fix merged.

**Comment by tha2015** [comment]
Can you please help to test v2.4.1? Thanks
https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties

**Comment by remal** [comment]
I confirm it works fine now, thanks!

**Comment by lynxplay** [comment]
Can confirm this properly works on my end as well :) Thank you for the quick merge 👍
