### ISSUE TITLE
The plugin does not work with Java 7

### ISSUE THREAD

**Issue by Endron** [n0mer/gradle-git-properties#21]
The version of the plugin available via the plugin exchange does not work when the build is executed with a Java 7 JDK. This is because the classes are compiled for Java 8 and are therefore incompatible with Java 7.
As the code is Groovy anyways the plugin could be compiled with the Java 7 targetCompatibility to ensure the plugin in the exchange is backwards compatible to Java 7. This is needed by these poor souls still forced to use Java 7 by there environment.

**Comment by Endron** [comment]
The pull request should have fixed this.

**Comment by n0mer** [comment]
Thank you @Endron !
