### ISSUE TITLE
Date format does not work

### ISSUE THREAD

**Issue by robertdanci** [n0mer/gradle-git-properties#24]
Hi, 

I've been trying the dateFormat feature with no success. I use the following config:

```
gitProperties {
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "GMT"
}
```

but the commit.time is still displayed as a number.

**Comment by mahanhz** [comment]
Had the same problem. I added single quotes around the Z and then it worked.

`gitProperties {
	dateFormat = "yyyy-MM-dd'T'HH:mm'Z'"
	dateFormatTimeZone = "GMT"
}`

**Comment by mahanhz** [comment]
Had the same issue. If I add milliseconds (.SSS) to the dateFormat then it works.

The below works for me:
gitProperties {
	dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ z"
	dateFormatTimeZone = "UTC"
}

**Comment by tha2015** [comment]
I tried your config with a simple project and it worked correctly. 
```
gitProperties {
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "GMT"
}
```
Can you try the attached zip file?

**Comment by n0mer** [comment]
@robertdanci closing this. Please open another ticket, in case you're still having trouble or date/time format proposed by @mahanhz is not working for you
