### ISSUE TITLE
How do you access Git Properties in Gradle?

### ISSUE THREAD

**Issue by pluttrell** [n0mer/gradle-git-properties#29]
Is there a way to get access to the git properties in the Gradle script itself? For example if I wanted to append the commit hash to the version number?

**Comment by nathansgreen** [comment]
I use this:

```gradle
apply plugin: 'org.ajoberstar.grgit'

version = "1.0.0-${grgit.head().abbreviatedId}"
```

**Comment by gclayburg** [comment]
I am using this inside a build.gradle task:

```
    File propertiesFile = new File("$buildDir/resources/main/git.properties")
    Properties properties = new Properties()
    propertiesFile.withInputStream {
        properties.load(it)
    }
    String mygitid = properties.'git.commit.id'
    println "git id is ${mygitid}"
```
My build is taking this git.commit.id value and inserting it into a LABEL of the docker image it creates.

I wonder if this is something that would be cleaner in a gradle plugin instead? Maybe this one?

**Comment by n0mer** [comment]
@pluttrell i'm using grgit library as well :)
