### ISSUE TITLE
Support git-describe

### ISSUE THREAD

**Issue by nathansgreen** [n0mer/gradle-git-properties#31]
`maven-git-commit-id-plugin` supports `git-describe`. In particular, it supports marking "dirty" working copies, so it's clear whether a given build was from a completely clean checkout. Any modification to a committed file will produce a dirty state, leading to a build that may not be reproducible.

**Comment by izeye** [comment]
@nathansgreen @n0mer Resolved via #32 ?

**Comment by n0mer** [comment]
@izeye @nathansgreen fixed in 1.4.18

**Comment by tha2015** [comment]
I compared the generated value for git.commit.id.describe and the values from "git describe" command and the git-commit-id-maven-plugin. The "git describe" command and the git-commit-id-maven-plugin generated the same value and they are different to value from this Gradle plugin. So I'd like to reopen this issue to review/update the implementation for git.commit.id.describe to make sure we are generating the same value as "git describe" and git-commit-id-maven-plugin.
