### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by toricoder** [n0mer/gradle-git-properties#37]
Hi, 
I am trying to build the project and getting an exception on the GitPropertiesPlugin class. It seems the bracket is not properly closed at the right place. 

`$ gradle build
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could                                                                                                                                                                                                not be reused, use --status for details
:compileJava NO-SOURCE
:compileGroovystartup failed:

GitPropertiesPlugin.groovy: 101: unexpected token: , @ line 101, column 24.
                          , (KEY_GIT_DIRTY)                : !repo.status().clean]
`

Thanks.

**Comment by n0mer** [comment]
@toricoder thanks for feedback, please try 1.4.18 version - there was error caused by merge.
