### ISSUE TITLE
Project repo url & dirty status

### ISSUE THREAD

**Issue by ErnestOrt** [n0mer/gradle-git-properties#40]
It would be great to be able to get github repo url on git.properties as well as if code has uncommit things as this plugin has:
```
<plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
</plugin>
```

Cheers!

**Comment by tha2015** [comment]
Should be fixed in next version 1.4.22

**Comment by tha2015** [comment]
Reopen the issue because the previous commit was reverted because of licensing issue

**Comment by tha2015** [comment]
Merged new code to fix the license issue. Will close this issue.
