### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by m91snik** [n0mer/gradle-git-properties#42]
Please, release new plugin version with this fix https://github.com/n0mer/gradle-git-properties/commit/3a440d6e7879a3cf913468adc222764a7993e601

**Comment by masonah** [comment]
Yes, I would also like to see this fix in the latest version. I am unable to toggle failOnNoGitDirectory to false in my build.gradle because it doesn't seem to exist in the GitPropertiesPluginExtension object in the current version.

**Comment by damienbeaufils** [comment]
+1

**Comment by n0mer** [comment]
@m91snik Nikolay, please find 1.4.18 version here https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties
