### ISSUE TITLE
Files for version 1.4.18 not accessible on https://plugins.gradle.org

### ISSUE THREAD

**Issue by tryptophane** [n0mer/gradle-git-properties#44]
I can't update to the new version, because the files seem not to have been uploaded correctly to the repo on https://plugins.gradle.org

Trying to download any of the files under this address fails:

https://plugins.gradle.org/m2/gradle/plugin/com/gorylenko/gradle-git-properties/gradle-git-properties/1.4.18/ 

A "gradle build --refresh-dependencies" will also fail...

**Comment by n0mer** [comment]
@tryptophane yes, i also noticed that.

Sent e-mail to gradle the day i published it, w/out any luck so far.

Will re-publish as next version later today.

Thanks for reaching out, anyway :)

**Comment by tryptophane** [comment]
Thank you Nikolay for your feedback and your work!

**Comment by n0mer** [comment]
@tryptophane please use 1.4.20 version.

I had to update gradle-publish-plugin from 0.9.1 to 0.9.9 (and, just in case, gradle itself to 4.2.1).

**Comment by tryptophane** [comment]
Thanks, now everything is fine :-)

**Comment by n0mer** [comment]
@tryptophane FYI - 1.4.21 is available.
