### ISSUE TITLE
Allow branch name to be overridden using env vars

### ISSUE THREAD

**Issue by behrangs-sportsbet** [n0mer/gradle-git-properties#46]
In Jenkins, some SCM plugins checkout a branch using `git checkout -f ...`:

```
Checking out Revision faf8f0c185c1cb091265f59027271ae1df18e850 (lorem/ipsum)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f faf8f0c185c1cb091265f59027271ae1df18e850
Commit message: "Lorem ipsum"
 > git rev-list 4053285d4f883630148ff48f38b50cace4d8d49f # timeout=10
```

When this happens, the branch name in `git.properties` is set to `HEAD`.

However, in the Jenkins environment the `BRANCH_NAME` env var preserves the actual branch name.

`gradle-git-properties` needs an option to query an env var for branch name, rather than `.git/...`.

**Comment by simongs** [comment]
In Jenkins, I have experienced the same issue.

In `git.properties' file (Expected = feature/test_branch)
```
git.branch=HEAD
```

**Comment by behrangs-sportsbet** [comment]
My PR should (#47) should fix this. @n0mer could you please review it?

**Comment by n0mer** [comment]
@behrangs-sportsbet LGTM

**Comment by tha2015** [comment]
@n0mer I compared this patch and the corresponding implementation for maven-git-commit-id plugin and found out that the maven plugin will automatically detect the Git branch from environment variable (GIT_LOCAL_BRANCH/GIT_BRANCH). See https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/GitDataProvider.java#L170 for the logic.
