### ISSUE TITLE
add branch tags

### ISSUE THREAD

**Issue by DemianTinkiel** [n0mer/gradle-git-properties#48]
like https://github.com/ktoso/maven-git-commit-id-plugin, could this support git.tag?

**Comment by tha2015** [comment]
This is related to issue #46 which was closed recently. But I still think the issue #46 was not resolved correctly (users will have to specify the branch name  while the issue #46 specifically requesting that the branch name must be detected automatically from environment variables).

I would suggest someone to submit to submit a new PR to fix this issue and #46 in a better way.

**Comment by dima767** [comment]
Yes, that would be super needed ;-)

**Comment by tha2015** [comment]
Should be fixed in next version 1.4.22

**Comment by dima767** [comment]
Are the snapshots available? If not, what is the estimated release date for `1.4.22`

**Comment by tha2015** [comment]
I guess we have to wait for @
