### ISSUE TITLE
'repository not found' error

### ISSUE THREAD

**Issue by robmoore** [n0mer/gradle-git-properties#49]
I have a project in a git repo that I've checked out locally and when I try to run `gradle build` I experience  the following error:
```
...
:generateGitProperties FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/rob/Work/IdeaProjects/my-project/.git/logs/refs/heads
...
```
The directory referred to above exists and the current branch is represented beneath it. I'd appreciate any tips to resolve this. I've tried removing the directory and cloning the repo again from scratch but it doesn't appear to make any difference.

**Comment by stefan-huettemann** [comment]
Having same problem on _some_ (!) of our repos:

```
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':server:generateGitProperties'.
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /opt/atlassian/pipelines/agent/build/.git/refs/remotes/origin
```

**Comment by matei-dragu** [comment]
Hey guys - any update on this issue?

**Comment by ka1eka** [comment]
Hi everybody,
I have created a PR, which fixes the issue: https://github.com/n0mer/gradle-git-properties/pull/50
As workaround (until this PR is merged) you may use the following procedure:
1. build the plugin locally from my fork:
```
./gradlew build
```
2. take ```gradle-git-properties-1.4.20.jar``` from ```build/libs``` folder and put it into you project repo into some folder. E.g. I put it into ```gradle/plugins/``` folder. 
3. Adjust your build.gradle:
```
buildscript {
	//...
	dependencies {
		//...
		classpath 'org.ajoberstar:gradle-git:1.4.2'
		classpath files('gradle/plugins/gradle-git-properties-1.4.20.jar')
	}
}
```
```org.ajoberstar:gradle-git:1.4.2``` - is the only dependency which is used by the plugin.

**Comment by n0mer** [comment]
@ka1eka i can build fresh release, gimme a sec

**Comment by n0mer** [comment]
after quick investigation - problem appeared when current working directory does not match, let's say, `jar.baseName` (e.g. in jenkins - where directory named after jenkins job, not after `jar.baseName`).

This PR fixes the issue - thanks for the valuable contribution!
