### ISSUE TITLE
task 'classes' not found

### ISSUE THREAD

**Issue by robmoore** [n0mer/gradle-git-properties#5]
I tried adding this to my build.gradle file and ran into the following error when building:
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.gorylenko.gradle-git-properties', version: '1.4.10']
> Failed to apply plugin [id 'com.gorylenko.gradle-git-properties']
   > Task with name 'classes' not found in root project 'my-project'.
```
It looks like it assumes that I will have a classes task and I don't.

**Comment by n0mer** [comment]
@robmoore this plugin does not deal with 'classes' task in any way.

Maybe this is due to up-to-date check from https://github.com/n0mer/gradle-git-properties/pull/4

**Comment by robmoore** [comment]
Odd. If I remove the plugin the issue isn't present and it wasn't present prior to adding the plugin.

**Comment by n0mer** [comment]
@robmoore please try previous version 1.4.7, will it work for you or not. This will show whether this error is caused by #4 or not :)

**Comment by thebignet** [comment]
@robmoore I've had this problem since 1.4.7. Try importing plugin the old way as described in https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties

**Comment by robmoore** [comment]
@thebignet Thanks for the tip. Using the old way works with 1.4.8 but not 1.4.9. 

@n0mer I tried using the new way with 1.4.7-1.4.10 with no joy.

**Comment by n0mer** [comment]
@robmoore @thebignet i'm also using the old mechanism of importing this plugin.

let's return to this conversation, when gradle new plugin system will graduate from beta.

**Comment by robmoore** [comment]
@n0mer It might be worth documenting this issue as I'm sure it will bite others. FWIW, I've used a number of other plugins using the new method and haven't had an issue with it until now.

BTW, I think I may be incorrect on what I said about the old way working with versions past 1.4.8. I just had to bump it back to 1.4.8.

**Comment by ezraroi** [comment]
Looks like also when using the old buildScript with any version (1.4.6 -1.4.10) i am getting the classes error

**Comment by sirgl** [comment]
I got this error again on version 1.4.17 with both old and new way of plugin import.
