### ISSUE TITLE
All properties are generated when configuring gitProperties { keys = [] }

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#57]
The behavior of the logic to handle **keys** property is counter intuitive. When I configuring **keys=[]**, I expected no property would be generated, but actually all properties were generated.

**Comment by n0mer** [comment]
i think, better to give some semantic:
* one list includedKeys = []
* second list excludedKeys = []

But, without this behaviour, empty always means "*" :)

**Comment by tha2015** [comment]
I think by default (not configuring keys), the keys property contains all keys, but users are allowed to configure it with any other list-type values (even an empty list). In the case an user explicitly uses empty list, no property will be created (if no custom property is configured). This will be easier to understand the plugin.
I believe that this issue (setting keys = []) is a corner case and its behavior can be changed without causing big issues.

**Comment by n0mer** [comment]
@tha2015 make sense, but in case of PR - please update README.md :)

**Comment by tha2015** [comment]
Sure, if I'm the one who submitting PR for this issue :-)

**Comment by n0mer** [comment]
fixed by #58
