### ISSUE TITLE
Replace  gitRepositoryRoot config key by dotGitDirectory config key

### ISSUE THREAD

**Issue by tha2015** [n0mer/gradle-git-properties#60]
I suggest that we should make a change (which is not backward compatible) to remove gitRepositoryRoot  config key and replace it by dotGitDirectory config key. There are several reasons for the suggestion:
1. Consistency. To be consistent with maven git commit id plugin
2. Flexibility of configuration. Currently gitRepositoryRoot must be configured to point to a parent folder which containing a subfolder with the name of ".git/" . This is not flexible enough to support for git modules (which using .git files or folders below ".git/modules/*")
3. Behavior change. We cannot fix issues regarding gitRepositoryRoot (i.e. changing its behavior) and still use the old config name. Adding a new name would make the config complicated.

@n0mer Should we break the compatibility and replace the config key? If yes, we might also want to replace gradle-git-1.7.2 by grgit 2.x (to fix #52) and will support Java 8+ only. The plugin's major version should also be changed to 2.0 or something to indicate that it will not backward compatible.

**Comment by n0mer** [comment]
@tha2015 i agree to support java8 since 2.x

**Comment by tha2015** [comment]
@n0mer should we also break compatibility and replace the gitRepositoryRoot  config key by dotGitDirectory config key?

**Comment by tha2015** [comment]
I created PR #62 for the suggestion. 
@n0mer It is also OK to ignore and close the PR without merging if you think we should not change the old key gitRepositoryRoot

**Comment by tha2015** [comment]
@n0mer I will go ahead and merge the PR to avoid conflicts when adding more changes for other issues. I assume that not many users are using gitRepositoryRoot and even if they are using, upgrading to the new version of the plugin should be super easy (just removing the gitRepositoryRoot key and the new logic will automatically detect the correct .git location - if it doesn't work, the dotGitDirectory can be used).
