### ISSUE TITLE
repository not found when .git is on a mounted drive.

### ISSUE THREAD

**Issue by dnnslmns** [n0mer/gradle-git-properties#79]
I have read other bug reports that suggest that this is solved, however it is still occuring under the following conditions:
Virtualbox VM Ubuntu 16.04
Mounted VM harddisk on /home/dennis/dev/project (project is the mounted folder containing the .git) 

* What went wrong:
Execution failed for task ':backend:generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/dennis/dev/project/.git/objects/pack

I checked and the folder does exist...

I did some analyses and came to the conclusion that the mount is causing this issue to reveal itself. 
Building the same project in a non mounted folder, worked like a charm.

This seems to be introduced in version 1.4.18+.. Version 1.4.17 works fine.

Cheers,
Dennis

**Comment by tha2015** [comment]
I believe that this is the same as issues #45 and #49 which was fixed from 1.4.21+

**Comment by dnnslmns** [comment]
For some reason it started working.. I was using 1.4.21 before when it gave the error..
