### ISSUE TITLE
Bump version to 1.5.0

### ISSUE THREAD

**Issue by clementboone** [n0mer/gradle-git-properties#80]
Hi,

First of all, thanks for the plugin.

- A lot of important changes have been added since last bump _1.4.21_. Could we expect the version **1.5.0** to be bumped and available on the _plugins.gradle.org_ repository quite soon?
- Also, because the repository is not having any tag, it's very hard and confusing to have clear idea of the state of the plugin for a given version : the current version suggested in your README.md is clearly not providing half of the API described in the same doc file. Could you please push a git tag of the version you bump so that we can have snapshots of the plugin for a given version? We could then easily differentiate master which is the trunk dev branch, and the tags which are fixed releases.

**Comment by tha2015** [comment]
Hi clementboone,

About the next version 1.4.22, I think we have to wait for @n0mer to publish a new version to Gradle plugins web site because I cannot do that. 

About the tagging:  I've created the tag v1.4.21 to identify correctly the features in version 1.4.21. See https://github.com/n0mer/gradle-git-properties/tree/v1.4.21 for more information.

Thank a lot for your suggestions.

**Comment by damienbeaufils** [comment]
Hello,

With all the changes that have been made since v1.4.21, I think the next release should be v1.5.0 instead of v1.4.22. WDYT?

**Comment by tha2015** [comment]
I agree. There are some important changes like supporting only Java 8+ and version changes of grgit and jgit libraries.

**Comment by clementboone** [comment]
Updated the issue tittle and content with version 1.5.0.
Thanks for the tag and quick answer

**Comment by tha2015** [comment]
Merged PR #89  to update version to 1.5.0

**Comment by clamothe** [comment]
@n0mer Could you release a new version?

**Comment by tha2015** [comment]
I'm not sure when we will have an official release, so I've created a 1.5.0-rc1 version for testing and published to my bintray repo at https://dl.bintray.com/tha/gradle-git-properties/
> Please note that it is not an official version, so do NOT use it in production.

How to use it from your build.gradle

``` groovy

buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        // repository for gradle-git-properties 1.5.0-rc1
        maven { 
            url "https://dl.bintray.com/tha/gradle-git-properties/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.5.0-rc1"
    }
}
apply plugin: "com.gorylenko.gradle-git-properties"

```

@n0mer Please help to release an official version, after that I will delete this rc1 version (to avoid having multiple versions at different repos).

**Comment by tha2015** [comment]
No. I cannot release a new version because I don't have necessary permissions on plugins.gradle.org to publish a new version.

About forking a new repo. I think we should give n0mer some time to release a new version (to avoid having many forked plugins). Of course, we will have to consider forking if n0mer cannot help us in next several months...

**Comment by n0mer** [comment]
@gwake1 will do this today

**Comment by n0mer** [comment]
```
:publishPlugins
Publishing plugin com.gorylenko.gradle-git-properties version 1.5.0
Publishing artifact build/libs/gradle-git-properties-1.5.0.jar
Publishing artifact build/libs/gradle-git-properties-1.5.0-sources.jar
Publishing artifact build/libs/gradle-git-properties-1.5.0-javadoc.jar
Publishing artifact build/libs/gradle-git-properties-1.5.0-groovydoc.jar
Publishing artifact build/publish-generated-resources/pom.xml
Activating plugin com.gorylenko.gradle-git-properties version 1.5.0

```

thanks for patience

**Comment by n0mer** [comment]
@tha2015 in case you need to release - please ping me on https://fb.com/n0mer or skype: nikolay.gorylenko

**Comment by varunmehta** [comment]
Tried and failed; Created: #107
