### ISSUE TITLE
Timestamp causes JAR hash change 

### ISSUE THREAD

**Issue by wwadge** [n0mer/gradle-git-properties#9]
``` #
#Fri Mar 04 14:27:29 CET 2016
git.commit.id=8ce443f105008d621430efe33f59816a77c428d8
git.commit.time=1457050640
....
```

The timestamp comment written to file causes gradle to think the resultant JAR file has changed even if nothing else has (and also causes issues with docker since it thinks the whole artifact has been modified). Can you suppress it?

**Comment by n0mer** [comment]
@wwadge did you try `keys` option from #3 ? Did it help to eliminate 'time' ?

**Comment by tha2015** [comment]
I think the ticket is about the comment "#Fri Mar 04 14:27:29 CET 2016", not about the key "git.commit.time=1457050640".

**Comment by wwadge** [comment]
That's correct @tha2015 -- keys option wouldn't do anything here.

**Comment by tha2015** [comment]
One thing I don't understand here is why the plugin is re-creating the git.properties while the input files and output files are not changed? Normally gradle will just show "UP-TO-DATE" and skip the step (assuming that the plugin is implemented correctly to support up-to-date check)

**Comment by wwadge** [comment]
Even if that is not not an issue, it doesn't hit my use case -- I am rebuilding each time from a jenkins clean slate but each time I build my docker images, docker will think they are new because of this timestamp which serves no purpose at all.

**Comment by n0mer** [comment]
@wwadge i published `1.4.13` , please give it a shot and tell whether comment is suppressed , and do you still have your issue.

**Comment by n0mer** [comment]
@wwadge please check 1.4.14 version and get back whether this fixes your issue or not

**Comment by wwadge** [comment]
Works fine - thanks!
